# Render Configuration File
# Clean deployment configuration for Construction Tracker

services:
  - type: web
    name: construction-tracker
    env: node
    plan: starter
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    healthCheckPath: /api/v1/health

# Build optimizations
build:
  commands:
    - echo "Starting clean build process..."
    - npm ci --only=production
    - cd client && npm ci && npm run build
    - echo "Build completed successfully"
