services:
  - type: web
    name: construction-tracker
    env: node
    buildCommand: |
      cd client
      npm install --legacy-peer-deps
      npm install -g cross-env
      npm run build
      cd ../server
      npm install
    startCommand: cd server && npm start
