services:
  - type: web
    name: construction-tracker
    env: node
    plan: starter
    nodeVersion: 18.18.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
