services:
  - type: web
    name: construction-tracker-webapp
    env: node
    plan: starter
    region: oregon  # or your preferred region
    nodeVersion: 18.18.0
    buildCommand: |
      echo "Installing dependencies..."
      npm install --production=false --no-optional
      cd client && npm install --legacy-peer-deps && npm run build
      cd ..
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      # Server Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024

      # MongoDB Configuration
      - key: MONGO_URI
        fromDatabase:
          name: construction-tracker-db
          property: connectionString

      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES
        value: "90"  # days

      # Client Configuration - Set to the Render service URL for API calls
      - key: REACT_APP_API_URL
        value: https://construction-tracker-webapp.onrender.com/api/v1
      
      # CORS Configuration
      - key: CORS_ORIGIN
        value: https://admin.servicesdsj.com
      - key: CORS_CREDENTIALS
        value: "true"
    envVarFiles:
      - group: production
        path: .env.production

    # Auto-deploy from GitHub
    autoDeploy: true
    branch: main

    # Health check configuration
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 300

    # Resource allocation
    plan: starter
    instanceSize: free
