services:
  - type: web
    name: construction-tracker
    env: node
    plan: starter
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
