services:
  - type: web
    name: construction-tracker
    env: node
    plan: starter
    nodeVersion: 20.9.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
